### ISSUE TITLE
Refactor invites?

### ISSUE THREAD

**Issue by turt2live** [bifurcation/ietf-mimi-protocol#37]
> **TODO**: For now, the invite flow implies that the user has to explicitly
> accept by adding one or more clients via external commit as part of the "Join"
> flow. In the future, we can either make the "Invite" flow more versatile and
> allow for Welcome based invitations, or create an additional "Add" flow, that
> allows participants to add other users (and their clients) directly via
> Welcome.

**Comment by kkohbrok** [comment]
That TODO is a bit outdated (meaning I forgot to remove it as part of the PR that added the Add flow). We now have an "Add" section in the document, so I think we can close this.
