### ISSUE TITLE
power levels or role-based authorization?

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/ietf-mimi-protocol#46]
draft-ralston-mimi-protocol currently uses Matrix-style power levels.
draft-barnes-mimi-protocol currently implies role-based access control (RBAC).

I think we have three reasonable choices here:
- keep using power levels
- use role-based access control with a fixed set of roles (for example: owner, admin, moderator, regular-user, visitor, banned, none)
- user role-based access control with administrator defined role labels. Each role label has a set of permissions it can accomplish (for example, can add user, can add remove user, can change user role, can change base policy, etc.)

Travis brought up that with role-based access control it is necessary to specify the behavior of combinations of roles or permissions. That is true, but I don't think it is unreasonable to enumerate those requirements. I think RBAC maps much better onto the variety of systems we would like to interop with.

**Comment by bifurcation** [comment]
DT call 2024-02-28:
* Violent agreement that RBAC+labels is a sensible way to go.  Specifically:
    * Underlying set of permissions 
    * Predefine labels for common sets of permissions
    * Allow administrators to define other sets of permissions
* @rohanmahy to make a PR with a minimal version of this scheme

**Comment by rohanmahy** [comment]
Created PR #62

**Comment by alvestrand** [comment]
Back in the LDAP days, we figured out that additive permissions (you can do the sum of all the roles that you are assigned) was possible to reason about.
Subtractive ACLs ("if you're in group FOO then you can do BAZ except when you're also in group BAR) made it almost impossible for users to figure out what policy they had specified.

That may be a warning - Keep It Simple.

**Comment by rohanmahy** [comment]
Merged #62. Closing.
