### ISSUE TITLE
Define the specific form that identifiers take in MIMI

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/ietf-mimi-protocol#53]

**Comment by bifurcation** [comment]
DT call 2024-02-28:
* @rohanmahy thinks URIs are the way to go.  Flexibility + compartmentalize vendor specifics
* @bifurcation and @raphaelrobert are more focused on requirements for identitiers -- what does an identifier need to do?
    * User/room -- connect to a provider, identify resource within a provider
    * Requirement to route to the MIMI app from outside the MIMI context?
* @ara4n points out that there are some cases where you want non-provider-specific identifiers
    * General feeling that (a) we will need provider-scoped things, and (b) mapping/discovery can add provider-independent stuff later
* @bifurcation Proposal: Make a simple URI scheme following the [Matrix URI scheme](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2312-matrix-uri.md )
    * `mimi://example.com/` 
    * `mimi://example.com/u/bifurcation`
    * `mimi://example.com/d/bifurcation/uuid`
    * `mimi://example.com/r/clubhouse`

**Comment by rohanmahy** [comment]
2 notes of things that are slightly different in this PR from what was discussed on the design team call
- the client/device identifier is shown as `mimi://example.com/d/{clientId}` but could have one or more path segments after the `/d/`.
- I added an MLS group identifier in case we want it to separately have a domain identifier. It is easy to remove if we don't want it.

**Comment by rohanmahy** [comment]
Closing as PR #59 was merged.
