### ISSUE TITLE
Make sure endpoint, and protocol are included in any MIMI signatures

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/ietf-mimi-protocol#55]

**Comment by rohanmahy** [comment]
@kkohbrok this only seems to apply to groupInfo/ requests and reponses. I made sure the Protocol is included. What threat are we solving by including the request endpoint?

**Comment by kkohbrok** [comment]
My main concern was to ensure that sender and recipient agree on what kind of request they're making. But now that I think about that's probably covered by including the payload name as label in the signature context. I think this is good to be closed as long as we keep properly labelling when signing.
